README.md, package.json, src/index.ts, src/test/mocks/TestDatasource.ts, src/utils/compatFeatures.test.ts, src/utils/compatFeatures.ts, src/utils/compatibility.test.ts, src/utils/compatibility.ts, src/utils/index.ts, src/utils/testDatasource.test.ts, src/utils/testDatasource.ts, yarn.lock
Issue: https://github.com/grafana/ui-enterprise/issues/38 - please read, there is a lot of context and screenshots which may help 🙏 
Supports the old format of error messages for users running Grafana <8, even when we have a new backend response coming from the plugin (for Grafana 8+).
Overriding the `testDatasource` function allows us to keep the new backend response and new core Grafana UI as it is for the new changes, but allow support for transforming what we send back from our plugin to core Grafana. This should improve maintainability.
Takes inspriration from https://github.com/marcusolsson/grafana-plugin-support/blob/c3f0272005d2e68142a756dbd85ad2df1ccbb962/src/utils/capability.ts
The addition of the new `compatibility.ts` and `compatFeatures.ts` files should also help us with …
=> feat: add compatibility check and health diagnostics compat feature

src/utils/compatFeatures.test.ts, src/utils/compatFeatures.ts, src/utils/index.ts
Add support for toggling our `healthDiagnosticsErrorsCompat` return.
This is because for the new health diagnostic error messages, we are planning to beta release them first so we want them to be switched off by default.
Usage in our plugins:
```
import { healthDiagnosticsErrorsCompat } from 'ui-enterprise';
import toggles from './featureToggles';
async testDatasource() {
return healthDiagnosticsErrorsCompat(super.testDatasource.bind(this), toggles.healthDiagnosticsErrors);
}
```
=> chore: add support for feature toggle for health diagnostics

src/components/index.ts
* Re-exporting InlineSwitch, CertificationKey from @grafana/ui package to support 7.2 in SAP HANA
=> Reexporting InlineSwitch and  CertificationKey

.circleci/config.yml, package.json, src/components/AsyncButtonCascader/AsyncButtonCascader.tsx, src/components/DataLinks/DataLink.tsx, src/components/DataLinks/DataLinks.tsx, src/components/DatePicker/styles.ts, src/components/QueryEditorRow/QueryEditorRow.tsx, src/test/mocks/DataQuery.ts, src/test/mocks/Datasource.ts, src/test/setupTests.ts, yarn.lock
These changes are to fix issues with
* newer versions of react
* newer versions of grafana libraries (useStyles2 vs useStyles)
* Update core libraries from Grafana 7 to Grafana 8 now that Grafana 9 is released.
=> Chore: Various changes to get plugin ui to compile with grafana 8 librarys

package.json, yarn.lock
Started getting react mismatch [error](https://drone.grafana.net/grafana/splunk-datasource/441/1/5) where a plugin uses this package.
version was added that differs from `8.4.7` [here](https://github.com/grafana/plugin-ui/commit/12f7c5968d0bbafb3efc48b1f99aae9fda35eece#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
=> match react version with 8.4.7

src/components/QueryEditor/QueryHeader.tsx, src/components/QueryEditor/RunQueryButton.tsx
Added run query button component like the one on this screen recording:
https://user-images.githubusercontent.com/1436174/227919287-73a4d88b-4bd4-4611-b3e2-b6b1d7203a54.mov
Previously the button in QueryHeader was the primary one with the "play" icon. I removed the icon and made it secondary based on [this discussion](https://github.com/grafana/jira-datasource/pull/149#discussion_r1144707420).
=> Extract RunQueryButton component from the QueryHeader

package.json, src/components/QueryEditor/RunQueryButton.tsx
When `dataTestId` wasn't passed it was rendered as `data-testid="false"`.
Before:
After:
=> fix: Prevent rendering data-testid="false" in RunQueryButton

package.json, src/unreleasedComponents/index.ts
Missed exporting these in the [previous PR](https://github.com/grafana/plugin-ui/pull/71)
=> fix: export recently added unreleased components

package.json, src/utils/changeset/index.ts, yarn.lock
Currently in some of our plugins we use [changeset](https://github.com/changesets/changesets) for generating `CHANGELOG.md`. We would like to be able to slightly change the changelog format and since changesets package has currently no API to achieve what we want, we will use this script for now.
It will add this prompt after the original command `yarn changeset` has completed:
And after running `yarn changeset version` it will update the changelog item generated by changesets package so that it looks like this:
| Before | After |
|--------|--------|
| ![image](https://github.com/grafana/plugin-ui/assets/1436174/4fda4a74-a352-4668-aa9c-4fd4402005fd) | ![image](https://github.com/grafana/plugin-ui/assets/1436174/f6592bb2-f50c-4a61-a356-6caad246bbce) |
=> feat: add script to be used in plugins for improving current changeset setup

package.json, src/utils/changeset/functions.ts
Currently we started to use `@changesets/cli/changelog` package to generate release lines and that adds commit hashes also. But for enterprise plugins source code is not public and commit hashes don't make sense in the changelog. So adding custom functions according to [this guide](https://github.com/changesets/changesets/blob/main/docs/modifying-changelog-format.md) so that we can use it to add only change summary to the changelog.
| Before | After |
|--------|--------|
| ![image](https://github.com/grafana/plugin-ui/assets/1436174/1eec8423-c8e3-47db-b181-36dd360bfccb) | ![image](https://github.com/grafana/plugin-ui/assets/1436174/aa26f690-6497-4563-bab2-a2b3676c10d8) |
=> feat: add changelog functions to avoid commit hash in release lines

CHANGELOG.md, package.json
before it was setup as a dev-dependency however this library is being used on the utils.ts file which can be required in other files.
therefore moving it to the dependencies should fix that dependency resolution conflict on other places we use plugin-ui
=> move user-event to dependencies

CHANGELOG.md, package.json, src/components/QueryEditor/QueryEditor.tsx, src/components/QueryEditor/types.ts
The DB.labels prop is marked as required even though the actual component that uses it marks it as optional: 
https://github.com/grafana/plugin-ui/blob/main/src/components/QueryEditor/QueryHeader.tsx#L46
This PR makes the key optional while also providing better type check for the expected map shape from QueryHeader:
https://github.com/grafana/plugin-ui/blob/main/src/components/QueryEditor/QueryHeader.tsx#L214
=> Db types fix

package.json, src/components/QueryEditor/QueryEditor.tsx, src/components/QueryEditor/QueryHeader.tsx, src/components/QueryEditor/types.ts, src/components/QueryEditor/utils/sql.utils.ts, src/components/QueryEditor/utils/useSqlChange.ts
currently if you want to disable datasets you need to do the following:
1. pass the `enableDatasets = false` prop into SqlQueryEditor.
2. provide a custom `toRawSql` function, that doesn't expect a dataset
this pr removes the need for code duplication in all datasources with disabled datasets by no longer requiring a custom `toRawSql` function.
this pr also also changes where you declare `disableDatasets`, this is now declared in datasource.ts opposed to previously this was just a prop in the builder component.
---
after this pr is merged, the only thing you need to do is add the flag `disableDatasets: true` to the getDB function inside of `datasource.ts`.
```ts
getDB(): DB {
return {
{... your other database options}
disableDatasets: true, // <---- just add this line here
};
}
```
=> improved way of disable datasets

package.json, src/components/QueryEditor/QueryHeader.tsx
at some point this component was changed and this caused a mis-match in the props.
the component expected `queryInvalid` but was actually passed `isQueryRunnable` which is the opposite boolean state.
this caused all error states to be reversed, here is an example in [databricks](https://github.com/grafana/plugins-private/blob/93da006af288067f252c65126278cd3b2b1d75f8/plugins/grafana-databricks-datasource/src/datasource.ts#L109-L114) where this caused a problem.
> @grafana/enterprise-datasources, when this is released, you will need to update the validateQuery function in the databricks ds to be the correct values again.
=> Fix the run query button

jest-setup.js, jest.config.js, jest/react-inlinesvg.tsx, jest/style.ts, package.json, src/components/ConfigEditor/SecureSocksProxyToggle.test.tsx, src/components/ConfigEditor/SecureSocksProxyToggle.tsx, src/components/CustomHeadersSettings/CustomHeadersSettings.test.tsx, src/components/DataLinks/DataLinks.test.tsx, src/components/Segment/Segment.test.tsx, src/components/Segment/Segment.tsx, src/index.ts, src/test/mocks/index.ts, src/test/mocks/style.ts, src/utils/compatFeatures.test.ts, src/utils/testDatasource.test.ts, yarn.lock
- Adds jest and testing library packages 
- Adds jest setup (mostly copied over from grafana-experimental)
- Improves tests with await userEvent, as well as some tests that were failing due to using fake timers (I think the reason was updates to jest/testing library that now handle timers differently but didn't investigate more thoroughly)
- Adds testing script to be added to the CI workflow
=> Add unit testing infrastructure

CHANGELOG.md, package.json
- Add unit testing infrastructure and script [#98](https://github.com/grafana/plugin-ui/pull/98)
- Add linting infrastructure and bump node version to 20 [#99](https://github.com/grafana/plugin-ui/pull/99)
- Add VisualQueryBuilder from grafana/experimental [#100](https://github.com/grafana/plugin-ui/pull/100)
- Improve build and lint scripts, add prettier and pre-commit hook [#101](https://github.com/grafana/plugin-ui/pull/101)
- Chore: Relax peer dependencies [#102](https://github.com/grafana/plugin-ui/pull/102)
- Move config editor components from grafana/experimental [#103](https://github.com/grafana/plugin-ui/pull/103)
- Migrate SQL editor from grafana/experimental [#104](https://github.com/grafana/plugin-ui/pull/104)
- Migrate Query Editor components from grafana/experimental …
=> prepare 0.9.0

src/components/ConfigEditor/Auth/index.ts, src/components/ConfigEditor/Auth/utils.ts, src/components/ConfigEditor/Connection/ConnectionSettings.tsx, src/components/ConfigEditor/index.ts, src/components/ConfigEditor/types.ts
I wanted the ability to use the "TLS settings" form portion in my plugin config editor.
**UPDATE**: I found a way to work with the `<Auth>` component by converting my "token" field into a `CustomMethod`, thus including it under the Authentication section.
~Since the `<TLSSettings>` component is not being exported, this PR aims to make it importable directly.~
**Update**: Importing `<Auth>` is sufficient. However it helps to change the type of `Config` so that I don't have to cast to `any`.
With the following workaround to the strict `Common` type, I am able to use this package without this PR:
```ts
const initialCommonConnectionConfig = useMemo(() => ({
jsonData,
secureJsonData: {},
secureJsonFields,
} as unknown as any), [jsonData, secureJsonFields])
```
- Redefine the `Config` type to …
=> feat: modify `Config` type so `<Auth>` component can be used on plugin  config pages

CHANGELOG.md, package.json, src/components/ConfigEditor/Auth/auth-method/AuthMethodSettings.tsx
Adds a little `<Field>` component and an `inputId` to the select dropdown so its easier to locate with playwright on e2e tests
Follows the [grafana testing guidelines](https://github.com/grafana/grafana/blob/401265522e584e4e71a1d92d5af311564b1ec33e/contribute/style-guides/testing.md)
=> chore: Auth make it more playwright friendly

CHANGELOG.md, package.json, src/components/ConfigEditor/types.ts
Related to changes in https://github.com/grafana/plugin-ui/pull/113
Fix `Config` type to be compatible with `DataSourceSettings` by making `secureJsonData` be optional https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L660
I noticed this when trying to use this package in grafana/grafana and got `Property 'secureJsonData' is optional in type 'DataSourceSettings<DataSourceJsonData, {}>' but required in type '{ jsonData: any; secureJsonData: {} | undefined; secureJsonFields: KeyValue<boolean>; }'` error. 
With optional `secureJsonData?`:
=> Fix `Config` type to be compatible with `DataSourceSettings`

CHANGELOG.md, package.json, rollup.config.ts, yarn.lock
CommonJS bundles are resolved via the package.json `main` and `exports['.'].require` properties in package.json but they currently point to non-existant `.cjs` files. This PR updates the rollup config to resolve this.
Builds now generate the `.cjs` files that were previously being written to the filesystem as `.js`.
=> Fix: Incorrect paths in package.json

CHANGELOG.md, package.json, src/index.ts
The mocks import was removed here: https://github.com/grafana/plugin-ui/pull/97
However mocks are still used on several enterprise packages so this reversal will allow us to migrate away from experimental, eg: https://github.com/grafana/plugins-private/blob/13be0ff2e6bc32838ef9875e21053a46af9e8c27/plugins/grafana-servicenow-datasource/src/components/__fixtures__/Datasource.ts#L3-L3
=> re-add test mocks

CHANGELOG.md, package.json, src/components/SQLEditor/standardSql/definition.ts
`require` breaks the Athena plugin (and Yugabyte) when I update to the latest version of plugin-ui. I assume the changes in the build process we did recently require `import` (heh) to be used here. I tested it locally with Athena and [Yugabyte](https://github.com/grafana/plugin-ui/commit/33971841e299ae4e1704b0d034144440921f6eaa) and both autocomplete and syntax highlighting features work with this change
=> Use import instead of require in SQL language definition + prepare 0.10.4

CHANGELOG.md, package.json, yarn.lock
https://github.com/grafana/grafana-dash-app/actions/runs/14313083700/job/40112690489?pr=34 fails because we need `@grafana/data@12.0.0`
=> Relax peer dependencies to work with everything newer than `10.4.0`

src/components/QueryEditor/AccessoryButton.tsx
- interfaces can only extend other interfaces (see https://www.typescriptlang.org/docs/handbook/2/objects.html#extending-types)
- in this case, `ButtonProps` is a `type` not an `interface`
- this seems to be working by accident currently, but will not work with changes planned in https://github.com/grafana/grafana/pull/109131
=> Chore: Define `AccessoryButton` types correctly

src/components/VisualQueryBuilder/components/QueryBuilderHints.tsx
I believe the source of a flaky test in Grafana is this set state being triggered from a place where we can't wrap it with act() correctly. 
https://github.com/grafana/grafana/actions/runs/16802657207/job/47587503434#step:6:91
Looking at the code, I don't see the reason why this should be state at all - it looks like it should be just useMemo.
=> QueryBuilderHints: Use useMemo instead of useState 

src/components/SQLEditor/components/SQLEditor.tsx, src/components/SQLEditor/hooks/useLatestCallback.ts
This PR resolves a stale closure issue in the SQLEditor component by introducing a `useLatestCallback` hook. This hook ensures the onChange callback _always_ references the latest version, preventing bugs from outdated closures. The `useLatestCallback` function effectively maintains a stable reference to the latest callback.
- Prevents Stale Closures: Ensures the latest callback is always used.
- Improves Performance: Minimizes unnecessary re-renders.
- Enhances Maintainability: Provides a reusable pattern for similar issues.
Fixes https://github.com/grafana/plugin-ui/issues/172
The Monaco editor's imperative APIs seems to capture initial state in callbacks, leading to stale closures and synchronization issues. The stale closure culprit, _I believe_, is the `onDidChangeModelContent` event …
=> SQLEditor: Fix stale closure

.github/workflows/publish-npm.yml
Setting up npm trusted publishing by following https://docs.google.com/document/d/1DmypU17btKJ6PkRacwBeI7HoM5nIGoc_ovKTuejaDC8/edit?tab=t.0
- Also moved the permissions block into the actual job
- Also removed triggering this pushes to `v0.0.x` branches since plugin-ui is on `0.10.10`
=> Use npm trusted publishing
